name: Check Code Quality and Create Pull Request

on:
  push:
    branches:
      - dev

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 --verbose .

  create_pull_request:
    runs-on: ubuntu-latest
    needs: code_quality
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          title: Automated Pull Request from dev to test
          body: Automated Pull Request created after successful code quality checks.
